#!/bin/bash

options=(
	# style=round
	width=4.0
	hidpi=off
	active_color="gradient(top_left=0xffff6767,bottom_right=0xffa277ff)"
	inactive_color=0x00414550
  background_color=0x10414550
  blur_radius=64
)

borders "${options[@]}"